version: '3'

services:
  api:
    restart: always
    build: ./api
    expose:
      - "3211"
    ports:
      - "3211:3211"
    depends_on:
      - postgres
  
  postgres:
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432
    build: ./postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password1234
        POSTGRES_DB: OrganizationControl

volumes:
  postgres_data: